name: RemoteIN Auto-Scraper

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch: 

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install aiohttp requests

      - name: Run Job Bot
        run: python bot.py

      - name: Commit and push updated jobs & companies
        run: |
          git config --global user.name "RemoteIN Bot"
          git config --global user.email "bot@remotein.local"
          git add jobs.json companies.json
          git commit -m "Auto-update jobs and expanded company database every hour" || exit 0
          git push